# Data settings
data:
  Use_TFRecord: True
  TFRecord_file: 'E:/SR_Train_Data/DF2K_bicubic_x4.tfrecord'
  train_lr_dir: 'data/train/lr_x4'
  train_hr_dir: 'data/train/hr'
  val_lr_dir: 'data/val/lr_x4'
  val_hr_dir: 'data/val/hr'
  eval_lr_dir: 'data/eval/lr_x4'
  eval_hr_dir: 'data/eval/hr'
  test_lr_dir: 'data/test/lr_x4'
  test_hr_dir: 'data/test/hr'
  cache_dir: ''
  lr_size: 32
  hr_size: 128
  upscale_factor: 4
  channels: 3
  batch_size: 1

# Training settings
training:
  iterations: 1000000
  save_every: 50
  init_learning_rate: !!float 1e-4
  lr_decay_iter_list: [ 200000, 400000,600000,800000 ]
  lr_decay_rate: 0.5

# Model checkpoints
checkpoint:
  latest_checkpoint_dir: 'outputs/checkpoints'
  best_weights_file: 'outputs/weights/best_weights.h5'
  history_file: 'outputs/history/history.json'

#logs
logs:
  eval_log_file: 'outputs/logs/eval/eval_log.txt'

